<a href="https://colab.research.google.com/github/divyansh1195/Halliburton-Landmark-Learning/blob/master/Data%20Science%20using%20Python(Halliburton)/Reshaping_Arrays_without_changing_the_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Reshaping Arrays without changing the data**

In [1]:
#An array is a data structure that stores values of same data type. In Python, this is the main difference between arrays and lists. 
#While python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to same data type#

In [2]:
import numpy as np

In [3]:
#create 2 arrays

In [4]:
X=np.arange(10)
print('The original Array:')
print(X)
print('\n')     

The original Array:
[0 1 2 3 4 5 6 7 8 9]




In [5]:
y=X.reshape(5,2)
print('The Modified Array:')
print (y)

The Modified Array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [6]:
#Checking Array Shape and Dimensions

In [7]:
X.ndim       

1

In [8]:
y.ndim

2

In [9]:
X.shape

(10,)

In [10]:
y.shape

(5, 2)

In [11]:
z=X.reshape(2,5)                     

In [12]:
z.ndim

2

In [13]:
z.shape

(2, 5)

In [14]:
#example 2
A=np.array([[1,2,3], [4,5,6]])

In [15]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
np.reshape(A,6)

array([1, 2, 3, 4, 5, 6])

In [17]:
np.reshape(A,6, order='F')#F-Fortran

array([1, 4, 2, 5, 3, 6])